[tool.poetry]
name = "nuitka-compile-traversable-bug"
version = "0.1.0"
description = ""
authors = ["Vladyslav Hnatiuk <aders1234@gmail.com>"]
readme = "README.md"
packages = [{include = "nuitka_compile_traversable_bug"}]

[tool.poetry.dependencies]
python = "^3.10"
Nuitka = "^1.4.7"


[tool.poetry.group.dev.dependencies]
ordered-set = "^4.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
