[tool.poetry]
name = "nuitka-async-iterator-bug"
version = "0.1.0"
description = ""
authors = ["Vladyslav Hnatiuk <aders1234@gmail.com>"]
readme = "README.md"
packages = [{include = "nuitka_async_iterator_bug"}]

[tool.poetry.dependencies]
python = "^3.10"
Nuitka = "^1.5.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
